apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    outputs:
      message: ${{ steps.write-message.outputs.message }}
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1

      - name: loop for many secs
        uses: docker://amazon/aws-cli
        shell: bash
        run: |
          echo "until loop - trigger run - 2"
          i=20
          until [ $i == 1 ]
          do
              echo "countdown: $i secs";
              i=$((i-1))
              sleep 1
          done
          echo "i value is $i"
          echo "loop terminated"
          exit 0
  