apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1

      - id: write-message
        name: write-message
        uses: docker://621104816052.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/alpine:latest
        run: |
          printf %s this-is-the-message > $CLOUDBEES_OUTPUTS/message

      - id: read-message
        name: read-message
        uses: docker://621104816052.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/alpine:latest
        run: |
          echo ${{ format('the messge passed from step write-message is - {0}', steps.write-message.outputs.message) }}

      - name: loop for many secs
        uses: docker://amazon/aws-cli
        shell: bash
        run: |
          echo "until loop - trigger run - 2"
          i=50
          until [ $i == 1 ]
          do
              echo "countdown: $i secs";
              i=$((i-1))
              sleep 1
          done
          echo "i value is $i"
          echo "loop terminated"
